component: website
name: website-8LR1yVPBQx
app: catalystdp-blog
stage: ${env:STAGE} #
inputs:
  src:
    src: ./public
    index: index.html
  region: ap-guangzhou
  bucketName: catalyst-static
  protocol: http
  isAutoCiDeploy: false
  replace: false
